function pickquit()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

%$Id: pickquit.m,v 3.0 2000/06/13 19:23:14 gilles Exp $
%$Log: pickquit.m,v $
%Revision 3.0  2000/06/13 19:23:14  gilles
%Release 3
%
%Revision 2.0  1999/05/21 18:47:56  mah
%Release 2
%
%Revision 1.1  1999/01/06 19:09:28  kay
%Initial revision
%
%
%Copyright (C) 1998 Seismology and Electromagnetic Section/
%Continental Geosciences Division/Geological Survey of Canada
%
%This library is free software; you can redistribute it and/or
%modify it under the terms of the GNU Library General Public
%License as published by the Free Software Foundation; either
%version 2 of the License, or (at your option) any later version.
%
%This library is distributed in the hope that it will be useful,
%but WITHOUT ANY WARRANTY; without even the implied warranty of
%MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%Library General Public License for more details.
%
%You should have received a copy of the GNU Library General Public
%License along with this library; if not, write to the
%Free Software Foundation, Inc., 59 Temple Place - Suite 330,
%Boston, MA  02111-1307, USA.
%
%DSI Consortium
%Continental Geosciences Division
%Geological Survey of Canada
%615 Booth St.
%Ottawa, Ontario
%K1A 0E9
%
%email: dsi@cg.nrcan.gc.ca

load pickquit

a = figure('Units','centimeters', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'NumberTitle','off', ...
	'Position',[0.388175 4.86712 15.0791 4.29979], ...
	'Tag','Fig2');
b = uicontrol('Parent',a, ...
	'Units','centimeters', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[1.01724 3.2547 10.6212 0.447896], ...
	'String','Save picks? Enter trace header word number, then click on `save`.', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','centimeters', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9.66668, ...
	'Position',[4.56852 2.31077 4.68796 0.585004], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','EditText1');
b = uicontrol('Parent',a, ...
	'Units','centimeters', ...
	'BackgroundColor',[0 1 1], ...
	'Callback',mat1, ...
	'FontSize',9.76192, ...
	'Position',[3.68003 0.836068 2.39351 0.92565], ...
	'String','Save', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','centimeters', ...
	'BackgroundColor',[0 1 1], ...
	'Callback','clear global ptimes,clear global temp,clear datasetname,close(gcbf)', ...
	'FontSize',9.76192, ...
	'Position',[7.85309 0.819007 2.23948 0.936008], ...
	'String','Do Not Save', ...
	'Tag','Pushbutton2');
